config/routes.rb
Rchon::Application.routes.draw do
  resources :research_appointment_materials

  resources :collection_location_entries

  resources :creator_book_relationships

  resources :accession_location_entries

  resources :creator_accession_relationships

  resources :collections

  resources :digital_content_files

  resources :digital_content_creator_relationships

  resources :collection_creator_relationships

  resources :digital_contents

  resources :user_fields

  resources :resarch_carts

  resources :research_appointments

  resources :research_appointment_purposes

  resources :material_types

  resources :locations

  resources :level_containers

  resources :extent_units

  resources :collection_contents

  resources :classifications

  resources :books

  resources :processing_priorities

  resources :accessions

  resources :repositories

  resources :subject_sources

  resources :subjects

  resources :creator_relationships

  resources :creators

  resources :creator_sources

end

app/models/collection.rb
class Collection < ActiveRecord::Base
  attr_accessible :abstract, :access_restrictions, :accrual_info, :acquisition_date, :acquisition_method, :acquisition_source, :alt_extent_statement, :appraisal_info, :arrangement, :biog_hist, :biog_hist_author, :classification_id, :collection_identifier, :custodial_history, :descpriptive_rules_id, :enabled, :extent, :extent_unit_id, :finding_aid_author, :finding_language_id, :inclusive_dates, :material_type_id, :normal_date_begin, :normal_date_end, :orig_copies_note, :orig_copies_url, :other_note, :other_url, :physical_access, :predominant_dates, :preferred_citation, :processing_info, :publication_date, :publication_note, :related_materials, :related_materials_url, :related_publications, :repository_id, :revision_history, :scope, :separated_materials, :sort_title, :technical_access, :title, :use_restrictions
  has_many :collection_contents, :dependent => :destroy
  belongs_to :classification
  belongs_to :repository
  belongs_to :material_type
  belongs_to :language
  belongs_to :extent_unit
  belongs_to :descriptive_rule
  has_many :collection_creator_relationships, :dependent => :destroy
  has_one :collection_location_entry,:dependent => :destroy
  has_many :accession_collection_relationships, :dependent => :destroy
  has_many :collection_subject_relationships, :dependent => :destroy
  has_many :collection_language_relationships, :dependent => :destroy
  has_many :digital_contents
  has_many :resarch_carts
  has_many :research_appointment_materials
  has_many :subjects, :through => :collection_subject_relationships
  has_many :languages, :through => :collection_language_relationships
  has_many :locations, :through => :collection_location_entries
  has_many  :creators, :through => :collection_creator_relationships
  has_many :accessions, :through => :accession_collection_relationships
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  # GET /collections
  # GET /collections.json
  def index
    @collections = Collection.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @collections }
    end
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
    @collection = Collection.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @collection }
    end
  end

  # GET /collections/new
  # GET /collections/new.json
  def new
    @collection = Collection.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @collection }
    end
  end

  # GET /collections/1/edit
  def edit
    @collection = Collection.find(params[:id])
  end

  # POST /collections
  # POST /collections.json
  def create
    @collection = Collection.new(params[:collection])

    respond_to do |format|
      if @collection.save
        format.html { redirect_to @collection, notice: 'Collection was successfully created.' }
        format.json { render json: @collection, status: :created, location: @collection }
      else
        format.html { render action: "new" }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /collections/1
  # PUT /collections/1.json
  def update
    @collection = Collection.find(params[:id])

    respond_to do |format|
      if @collection.update_attributes(params[:collection])
        format.html { redirect_to @collection, notice: 'Collection was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection = Collection.find(params[:id])
    @collection.destroy

    respond_to do |format|
      format.html { redirect_to collections_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_form.html.erb
<%= form_for(@collection) do |f| %>
  <% if @collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
      <% @collection.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :enabled %><br />
    <%= f.check_box :enabled %>
  </div>
  <div class="field">
    <%= f.label :extent %><br />
    <%= f.text_field :extent %>
  </div>
  <div class="field">
    <%= f.label :collection_identifier %><br />
    <%= f.text_field :collection_identifier %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :sort_title %><br />
    <%= f.text_field :sort_title %>
  </div>
  <div class="field">
    <%= f.label :inclusive_dates %><br />
    <%= f.text_field :inclusive_dates %>
  </div>
  <div class="field">
    <%= f.label :predominant_dates %><br />
    <%= f.text_field :predominant_dates %>
  </div>
  <div class="field">
    <%= f.label :acquisition_date %><br />
    <%= f.text_field :acquisition_date %>
  </div>
  <div class="field">
    <%= f.label :orig_copies_url %><br />
    <%= f.text_field :orig_copies_url %>
  </div>
  <div class="field">
    <%= f.label :related_materials_url %><br />
    <%= f.text_field :related_materials_url %>
  </div>
  <div class="field">
    <%= f.label :publication_date %><br />
    <%= f.text_field :publication_date %>
  </div>
  <div class="field">
    <%= f.label :biog_hist_author %><br />
    <%= f.text_field :biog_hist_author %>
  </div>
  <div class="field">
    <%= f.label :finding_aid_author %><br />
    <%= f.text_field :finding_aid_author %>
  </div>
  <div class="field">
    <%= f.label :repository_id %><br />
    <%= f.number_field :repository_id %>
  </div>
  <div class="field">
    <%= f.label :classification_id %><br />
    <%= f.number_field :classification_id %>
  </div>
  <div class="field">
    <%= f.label :descpriptive_rules_id %><br />
    <%= f.number_field :descpriptive_rules_id %>
  </div>
  <div class="field">
    <%= f.label :finding_language_id %><br />
    <%= f.number_field :finding_language_id %>
  </div>
  <div class="field">
    <%= f.label :normal_date_begin %><br />
    <%= f.number_field :normal_date_begin %>
  </div>
  <div class="field">
    <%= f.label :normal_date_end %><br />
    <%= f.number_field :normal_date_end %>
  </div>
  <div class="field">
    <%= f.label :extent_unit_id %><br />
    <%= f.number_field :extent_unit_id %>
  </div>
  <div class="field">
    <%= f.label :material_type_id %><br />
    <%= f.number_field :material_type_id %>
  </div>
  <div class="field">
    <%= f.label :scope %><br />
    <%= f.text_area :scope %>
  </div>
  <div class="field">
    <%= f.label :abstract %><br />
    <%= f.text_area :abstract %>
  </div>
  <div class="field">
    <%= f.label :arrangement %><br />
    <%= f.text_area :arrangement %>
  </div>
  <div class="field">
    <%= f.label :alt_extent_statement %><br />
    <%= f.text_area :alt_extent_statement %>
  </div>
  <div class="field">
    <%= f.label :access_restrictions %><br />
    <%= f.text_area :access_restrictions %>
  </div>
  <div class="field">
    <%= f.label :use_restrictions %><br />
    <%= f.text_area :use_restrictions %>
  </div>
  <div class="field">
    <%= f.label :physical_access %><br />
    <%= f.text_area :physical_access %>
  </div>
  <div class="field">
    <%= f.label :technical_access %><br />
    <%= f.text_area :technical_access %>
  </div>
  <div class="field">
    <%= f.label :acquisition_source %><br />
    <%= f.text_area :acquisition_source %>
  </div>
  <div class="field">
    <%= f.label :acquisition_method %><br />
    <%= f.text_area :acquisition_method %>
  </div>
  <div class="field">
    <%= f.label :appraisal_info %><br />
    <%= f.text_area :appraisal_info %>
  </div>
  <div class="field">
    <%= f.label :accrual_info %><br />
    <%= f.text_area :accrual_info %>
  </div>
  <div class="field">
    <%= f.label :custodial_history %><br />
    <%= f.text_area :custodial_history %>
  </div>
  <div class="field">
    <%= f.label :orig_copies_note %><br />
    <%= f.text_area :orig_copies_note %>
  </div>
  <div class="field">
    <%= f.label :related_materials %><br />
    <%= f.text_area :related_materials %>
  </div>
  <div class="field">
    <%= f.label :related_publications %><br />
    <%= f.text_area :related_publications %>
  </div>
  <div class="field">
    <%= f.label :separated_materials %><br />
    <%= f.text_area :separated_materials %>
  </div>
  <div class="field">
    <%= f.label :preferred_citation %><br />
    <%= f.text_area :preferred_citation %>
  </div>
  <div class="field">
    <%= f.label :other_note %><br />
    <%= f.text_area :other_note %>
  </div>
  <div class="field">
    <%= f.label :other_url %><br />
    <%= f.text_area :other_url %>
  </div>
  <div class="field">
    <%= f.label :processing_info %><br />
    <%= f.text_area :processing_info %>
  </div>
  <div class="field">
    <%= f.label :revision_history %><br />
    <%= f.text_area :revision_history %>
  </div>
  <div class="field">
    <%= f.label :publication_note %><br />
    <%= f.text_area :publication_note %>
  </div>
  <div class="field">
    <%= f.label :biog_hist %><br />
    <%= f.text_area :biog_hist %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/collections/edit.html.erb
<h1>Editing collection</h1>

<%= render 'form' %>

<%= link_to 'Show', @collection %> |
<%= link_to 'Back', collections_path %>

app/views/collections/index.html.erb
<h1>Listing collections</h1>

<table>
  <tr>
    <th>Enabled</th>
    <th>Extent</th>
    <th>Collection identifier</th>
    <th>Title</th>
    <th>Sort title</th>
    <th>Inclusive dates</th>
    <th>Predominant dates</th>
    <th>Acquisition date</th>
    <th>Orig copies url</th>
    <th>Related materials url</th>
    <th>Publication date</th>
    <th>Biog hist author</th>
    <th>Finding aid author</th>
    <th>Repository</th>
    <th>Classification</th>
    <th>Descpriptive rules</th>
    <th>Finding language</th>
    <th>Normal date begin</th>
    <th>Normal date end</th>
    <th>Extent unit</th>
    <th>Material type</th>
    <th>Scope</th>
    <th>Abstract</th>
    <th>Arrangement</th>
    <th>Alt extent statement</th>
    <th>Access restrictions</th>
    <th>Use restrictions</th>
    <th>Physical access</th>
    <th>Technical access</th>
    <th>Acquisition source</th>
    <th>Acquisition method</th>
    <th>Appraisal info</th>
    <th>Accrual info</th>
    <th>Custodial history</th>
    <th>Orig copies note</th>
    <th>Related materials</th>
    <th>Related publications</th>
    <th>Separated materials</th>
    <th>Preferred citation</th>
    <th>Other note</th>
    <th>Other url</th>
    <th>Processing info</th>
    <th>Revision history</th>
    <th>Publication note</th>
    <th>Biog hist</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @collections.each do |collection| %>
  <tr>
    <td><%= collection.enabled %></td>
    <td><%= collection.extent %></td>
    <td><%= collection.collection_identifier %></td>
    <td><%= collection.title %></td>
    <td><%= collection.sort_title %></td>
    <td><%= collection.inclusive_dates %></td>
    <td><%= collection.predominant_dates %></td>
    <td><%= collection.acquisition_date %></td>
    <td><%= collection.orig_copies_url %></td>
    <td><%= collection.related_materials_url %></td>
    <td><%= collection.publication_date %></td>
    <td><%= collection.biog_hist_author %></td>
    <td><%= collection.finding_aid_author %></td>
    <td><%= collection.repository_id %></td>
    <td><%= collection.classification_id %></td>
    <td><%= collection.descpriptive_rules_id %></td>
    <td><%= collection.finding_language_id %></td>
    <td><%= collection.normal_date_begin %></td>
    <td><%= collection.normal_date_end %></td>
    <td><%= collection.extent_unit_id %></td>
    <td><%= collection.material_type_id %></td>
    <td><%= collection.scope %></td>
    <td><%= collection.abstract %></td>
    <td><%= collection.arrangement %></td>
    <td><%= collection.alt_extent_statement %></td>
    <td><%= collection.access_restrictions %></td>
    <td><%= collection.use_restrictions %></td>
    <td><%= collection.physical_access %></td>
    <td><%= collection.technical_access %></td>
    <td><%= collection.acquisition_source %></td>
    <td><%= collection.acquisition_method %></td>
    <td><%= collection.appraisal_info %></td>
    <td><%= collection.accrual_info %></td>
    <td><%= collection.custodial_history %></td>
    <td><%= collection.orig_copies_note %></td>
    <td><%= collection.related_materials %></td>
    <td><%= collection.related_publications %></td>
    <td><%= collection.separated_materials %></td>
    <td><%= collection.preferred_citation %></td>
    <td><%= collection.other_note %></td>
    <td><%= collection.other_url %></td>
    <td><%= collection.processing_info %></td>
    <td><%= collection.revision_history %></td>
    <td><%= collection.publication_note %></td>
    <td><%= collection.biog_hist %></td>
    <td><%= link_to 'Show', collection %></td>
    <td><%= link_to 'Edit', edit_collection_path(collection) %></td>
    <td><%= link_to 'Destroy', collection, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Collection', new_collection_path %>

app/views/collections/new.html.erb
<h1>New collection</h1>

<%= render 'form' %>

<%= link_to 'Back', collections_path %>

app/views/collections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Enabled:</b>
  <%= @collection.enabled %>
</p>

<p>
  <b>Extent:</b>
  <%= @collection.extent %>
</p>

<p>
  <b>Collection identifier:</b>
  <%= @collection.collection_identifier %>
</p>

<p>
  <b>Title:</b>
  <%= @collection.title %>
</p>

<p>
  <b>Sort title:</b>
  <%= @collection.sort_title %>
</p>

<p>
  <b>Inclusive dates:</b>
  <%= @collection.inclusive_dates %>
</p>

<p>
  <b>Predominant dates:</b>
  <%= @collection.predominant_dates %>
</p>

<p>
  <b>Acquisition date:</b>
  <%= @collection.acquisition_date %>
</p>

<p>
  <b>Orig copies url:</b>
  <%= @collection.orig_copies_url %>
</p>

<p>
  <b>Related materials url:</b>
  <%= @collection.related_materials_url %>
</p>

<p>
  <b>Publication date:</b>
  <%= @collection.publication_date %>
</p>

<p>
  <b>Biog hist author:</b>
  <%= @collection.biog_hist_author %>
</p>

<p>
  <b>Finding aid author:</b>
  <%= @collection.finding_aid_author %>
</p>

<p>
  <b>Repository:</b>
  <%= @collection.repository_id %>
</p>

<p>
  <b>Classification:</b>
  <%= @collection.classification_id %>
</p>

<p>
  <b>Descpriptive rules:</b>
  <%= @collection.descpriptive_rules_id %>
</p>

<p>
  <b>Finding language:</b>
  <%= @collection.finding_language_id %>
</p>

<p>
  <b>Normal date begin:</b>
  <%= @collection.normal_date_begin %>
</p>

<p>
  <b>Normal date end:</b>
  <%= @collection.normal_date_end %>
</p>

<p>
  <b>Extent unit:</b>
  <%= @collection.extent_unit_id %>
</p>

<p>
  <b>Material type:</b>
  <%= @collection.material_type_id %>
</p>

<p>
  <b>Scope:</b>
  <%= @collection.scope %>
</p>

<p>
  <b>Abstract:</b>
  <%= @collection.abstract %>
</p>

<p>
  <b>Arrangement:</b>
  <%= @collection.arrangement %>
</p>

<p>
  <b>Alt extent statement:</b>
  <%= @collection.alt_extent_statement %>
</p>

<p>
  <b>Access restrictions:</b>
  <%= @collection.access_restrictions %>
</p>

<p>
  <b>Use restrictions:</b>
  <%= @collection.use_restrictions %>
</p>

<p>
  <b>Physical access:</b>
  <%= @collection.physical_access %>
</p>

<p>
  <b>Technical access:</b>
  <%= @collection.technical_access %>
</p>

<p>
  <b>Acquisition source:</b>
  <%= @collection.acquisition_source %>
</p>

<p>
  <b>Acquisition method:</b>
  <%= @collection.acquisition_method %>
</p>

<p>
  <b>Appraisal info:</b>
  <%= @collection.appraisal_info %>
</p>

<p>
  <b>Accrual info:</b>
  <%= @collection.accrual_info %>
</p>

<p>
  <b>Custodial history:</b>
  <%= @collection.custodial_history %>
</p>

<p>
  <b>Orig copies note:</b>
  <%= @collection.orig_copies_note %>
</p>

<p>
  <b>Related materials:</b>
  <%= @collection.related_materials %>
</p>

<p>
  <b>Related publications:</b>
  <%= @collection.related_publications %>
</p>

<p>
  <b>Separated materials:</b>
  <%= @collection.separated_materials %>
</p>

<p>
  <b>Preferred citation:</b>
  <%= @collection.preferred_citation %>
</p>

<p>
  <b>Other note:</b>
  <%= @collection.other_note %>
</p>

<p>
  <b>Other url:</b>
  <%= @collection.other_url %>
</p>

<p>
  <b>Processing info:</b>
  <%= @collection.processing_info %>
</p>

<p>
  <b>Revision history:</b>
  <%= @collection.revision_history %>
</p>

<p>
  <b>Publication note:</b>
  <%= @collection.publication_note %>
</p>

<p>
  <b>Biog hist:</b>
  <%= @collection.biog_hist %>
</p>


<%= link_to 'Edit', edit_collection_path(@collection) %> |
<%= link_to 'Back', collections_path %>