config/routes.rb
Rchon::Application.routes.draw do
  resources :research_appointment_materials

  resources :collection_location_entries

  resources :creator_book_relationships

  resources :accession_location_entries

  resources :creator_accession_relationships

  resources :collections

  resources :digital_content_files

  resources :digital_content_creator_relationships

  resources :collection_creator_relationships

  resources :digital_contents

  resources :user_fields

  resources :resarch_carts

  resources :research_appointments

  resources :research_appointment_purposes

  resources :material_types

  resources :locations

  resources :level_containers

  resources :extent_units

  resources :collection_contents

  resources :classifications

  resources :books

  resources :processing_priorities

  resources :accessions

  resources :repositories

  resources :subject_sources

  resources :subjects

  resources :creator_relationships

  resources :creators

  resources :creator_sources

end

app/models/repository.rb
class Repository < ActiveRecord::Base
  attr_accessible :address, :address2, :administrator, :city, :code, :country, :email, :email_signature, :fax, :name, :phone, :phone_ext, :research_functionality, :state, :url, :zip
  belongs_to :country
  has_many :collections
  has_many :creators
  has_many :location_repository_relationships, :dependent => :destroy
  has_many :user_repository_relationships, :dependent => :destroy
  has_many :users, :through => :user_repository_relationships
  has_many :locations, :through => :location_repository_relationships
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  # GET /repositories
  # GET /repositories.json
  def index
    @repositories = Repository.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @repositories }
    end
  end

  # GET /repositories/1
  # GET /repositories/1.json
  def show
    @repository = Repository.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @repository }
    end
  end

  # GET /repositories/new
  # GET /repositories/new.json
  def new
    @repository = Repository.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @repository }
    end
  end

  # GET /repositories/1/edit
  def edit
    @repository = Repository.find(params[:id])
  end

  # POST /repositories
  # POST /repositories.json
  def create
    @repository = Repository.new(params[:repository])

    respond_to do |format|
      if @repository.save
        format.html { redirect_to @repository, notice: 'Repository was successfully created.' }
        format.json { render json: @repository, status: :created, location: @repository }
      else
        format.html { render action: "new" }
        format.json { render json: @repository.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /repositories/1
  # PUT /repositories/1.json
  def update
    @repository = Repository.find(params[:id])

    respond_to do |format|
      if @repository.update_attributes(params[:repository])
        format.html { redirect_to @repository, notice: 'Repository was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @repository.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repositories/1
  # DELETE /repositories/1.json
  def destroy
    @repository = Repository.find(params[:id])
    @repository.destroy

    respond_to do |format|
      format.html { redirect_to repositories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/repositories_helper.rb
module RepositoriesHelper
end

app/views/repositories/_form.html.erb
<%= form_for(@repository) do |f| %>
  <% if @repository.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@repository.errors.count, "error") %> prohibited this repository from being saved:</h2>

      <ul>
      <% @repository.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :administrator %><br />
    <%= f.text_field :administrator %>
  </div>
  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :address2 %><br />
    <%= f.text_field :address2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :zip %><br />
    <%= f.number_field :zip %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :phone_ext %><br />
    <%= f.text_field :phone_ext %>
  </div>
  <div class="field">
    <%= f.label :fax %><br />
    <%= f.text_field :fax %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :email_signature %><br />
    <%= f.text_area :email_signature %>
  </div>
  <div class="field">
    <%= f.label :research_functionality %><br />
    <%= f.number_field :research_functionality %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/repositories/edit.html.erb
<h1>Editing repository</h1>

<%= render 'form' %>

<%= link_to 'Show', @repository %> |
<%= link_to 'Back', repositories_path %>

app/views/repositories/index.html.erb
<h1>Listing repositories</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Administrator</th>
    <th>Code</th>
    <th>Address</th>
    <th>Address2</th>
    <th>City</th>
    <th>State</th>
    <th>Country</th>
    <th>Zip</th>
    <th>Phone</th>
    <th>Phone ext</th>
    <th>Fax</th>
    <th>Email</th>
    <th>Url</th>
    <th>Email signature</th>
    <th>Research functionality</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @repositories.each do |repository| %>
  <tr>
    <td><%= repository.name %></td>
    <td><%= repository.administrator %></td>
    <td><%= repository.code %></td>
    <td><%= repository.address %></td>
    <td><%= repository.address2 %></td>
    <td><%= repository.city %></td>
    <td><%= repository.state %></td>
    <td><%= repository.country %></td>
    <td><%= repository.zip %></td>
    <td><%= repository.phone %></td>
    <td><%= repository.phone_ext %></td>
    <td><%= repository.fax %></td>
    <td><%= repository.email %></td>
    <td><%= repository.url %></td>
    <td><%= repository.email_signature %></td>
    <td><%= repository.research_functionality %></td>
    <td><%= link_to 'Show', repository %></td>
    <td><%= link_to 'Edit', edit_repository_path(repository) %></td>
    <td><%= link_to 'Destroy', repository, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Repository', new_repository_path %>

app/views/repositories/new.html.erb
<h1>New repository</h1>

<%= render 'form' %>

<%= link_to 'Back', repositories_path %>

app/views/repositories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @repository.name %>
</p>

<p>
  <b>Administrator:</b>
  <%= @repository.administrator %>
</p>

<p>
  <b>Code:</b>
  <%= @repository.code %>
</p>

<p>
  <b>Address:</b>
  <%= @repository.address %>
</p>

<p>
  <b>Address2:</b>
  <%= @repository.address2 %>
</p>

<p>
  <b>City:</b>
  <%= @repository.city %>
</p>

<p>
  <b>State:</b>
  <%= @repository.state %>
</p>

<p>
  <b>Country:</b>
  <%= @repository.country %>
</p>

<p>
  <b>Zip:</b>
  <%= @repository.zip %>
</p>

<p>
  <b>Phone:</b>
  <%= @repository.phone %>
</p>

<p>
  <b>Phone ext:</b>
  <%= @repository.phone_ext %>
</p>

<p>
  <b>Fax:</b>
  <%= @repository.fax %>
</p>

<p>
  <b>Email:</b>
  <%= @repository.email %>
</p>

<p>
  <b>Url:</b>
  <%= @repository.url %>
</p>

<p>
  <b>Email signature:</b>
  <%= @repository.email_signature %>
</p>

<p>
  <b>Research functionality:</b>
  <%= @repository.research_functionality %>
</p>


<%= link_to 'Edit', edit_repository_path(@repository) %> |
<%= link_to 'Back', repositories_path %>