config/routes.rb
Rchon::Application.routes.draw do
  resources :research_appointment_materials

  resources :collection_location_entries

  resources :creator_book_relationships

  resources :accession_location_entries

  resources :creator_accession_relationships

  resources :collections

  resources :digital_content_files

  resources :digital_content_creator_relationships

  resources :collection_creator_relationships

  resources :digital_contents

  resources :user_fields

  resources :resarch_carts

  resources :research_appointments

  resources :research_appointment_purposes

  resources :material_types

  resources :locations

  resources :level_containers

  resources :extent_units

  resources :collection_contents

  resources :classifications

  resources :books

  resources :processing_priorities

  resources :accessions

  resources :repositories

  resources :subject_sources

  resources :subjects

  resources :creator_relationships

  resources :creators

  resources :creator_sources

end

app/models/subject_source.rb
class SubjectSource < ActiveRecord::Base
  attr_accessible :ead_source, :subject_source
  has_many :subjects
end

app/controllers/subject_sources_controller.rb
class SubjectSourcesController < ApplicationController
  # GET /subject_sources
  # GET /subject_sources.json
  def index
    @subject_sources = SubjectSource.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subject_sources }
    end
  end

  # GET /subject_sources/1
  # GET /subject_sources/1.json
  def show
    @subject_source = SubjectSource.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subject_source }
    end
  end

  # GET /subject_sources/new
  # GET /subject_sources/new.json
  def new
    @subject_source = SubjectSource.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subject_source }
    end
  end

  # GET /subject_sources/1/edit
  def edit
    @subject_source = SubjectSource.find(params[:id])
  end

  # POST /subject_sources
  # POST /subject_sources.json
  def create
    @subject_source = SubjectSource.new(params[:subject_source])

    respond_to do |format|
      if @subject_source.save
        format.html { redirect_to @subject_source, notice: 'Subject source was successfully created.' }
        format.json { render json: @subject_source, status: :created, location: @subject_source }
      else
        format.html { render action: "new" }
        format.json { render json: @subject_source.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /subject_sources/1
  # PUT /subject_sources/1.json
  def update
    @subject_source = SubjectSource.find(params[:id])

    respond_to do |format|
      if @subject_source.update_attributes(params[:subject_source])
        format.html { redirect_to @subject_source, notice: 'Subject source was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @subject_source.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subject_sources/1
  # DELETE /subject_sources/1.json
  def destroy
    @subject_source = SubjectSource.find(params[:id])
    @subject_source.destroy

    respond_to do |format|
      format.html { redirect_to subject_sources_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/subject_sources_helper.rb
module SubjectSourcesHelper
end

app/views/subject_sources/_form.html.erb
<%= form_for(@subject_source) do |f| %>
  <% if @subject_source.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subject_source.errors.count, "error") %> prohibited this subject_source from being saved:</h2>

      <ul>
      <% @subject_source.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subject_source %><br />
    <%= f.text_field :subject_source %>
  </div>
  <div class="field">
    <%= f.label :ead_source %><br />
    <%= f.text_field :ead_source %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subject_sources/edit.html.erb
<h1>Editing subject_source</h1>

<%= render 'form' %>

<%= link_to 'Show', @subject_source %> |
<%= link_to 'Back', subject_sources_path %>

app/views/subject_sources/index.html.erb
<h1>Listing subject_sources</h1>

<table>
  <tr>
    <th>Subject source</th>
    <th>Ead source</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @subject_sources.each do |subject_source| %>
  <tr>
    <td><%= subject_source.subject_source %></td>
    <td><%= subject_source.ead_source %></td>
    <td><%= link_to 'Show', subject_source %></td>
    <td><%= link_to 'Edit', edit_subject_source_path(subject_source) %></td>
    <td><%= link_to 'Destroy', subject_source, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Subject source', new_subject_source_path %>

app/views/subject_sources/new.html.erb
<h1>New subject_source</h1>

<%= render 'form' %>

<%= link_to 'Back', subject_sources_path %>

app/views/subject_sources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Subject source:</b>
  <%= @subject_source.subject_source %>
</p>

<p>
  <b>Ead source:</b>
  <%= @subject_source.ead_source %>
</p>


<%= link_to 'Edit', edit_subject_source_path(@subject_source) %> |
<%= link_to 'Back', subject_sources_path %>