config/routes.rb
Rchon::Application.routes.draw do
  resources :research_appointment_materials

  resources :collection_location_entries

  resources :creator_book_relationships

  resources :accession_location_entries

  resources :creator_accession_relationships

  resources :collections

  resources :digital_content_files

  resources :digital_content_creator_relationships

  resources :collection_creator_relationships

  resources :digital_contents

  resources :user_fields

  resources :resarch_carts

  resources :research_appointments

  resources :research_appointment_purposes

  resources :material_types

  resources :locations

  resources :level_containers

  resources :extent_units

  resources :collection_contents

  resources :classifications

  resources :books

  resources :processing_priorities

  resources :accessions

  resources :repositories

  resources :subject_sources

  resources :subjects

  resources :creator_relationships

  resources :creators

  resources :creator_sources

end

app/models/collection_creator_relationship.rb
class CollectionCreatorRelationship < ActiveRecord::Base
  attr_accessible :collection_id, :creator_id, :primary_creator
  belongs_to :collection
  belongs_to :creator
  validates_presence_of :collection_id
  validates_presence_of :creator_id
end

app/controllers/collection_creator_relationships_controller.rb
class CollectionCreatorRelationshipsController < ApplicationController
  # GET /collection_creator_relationships
  # GET /collection_creator_relationships.json
  def index
    @collection_creator_relationships = CollectionCreatorRelationship.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @collection_creator_relationships }
    end
  end

  # GET /collection_creator_relationships/1
  # GET /collection_creator_relationships/1.json
  def show
    @collection_creator_relationship = CollectionCreatorRelationship.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @collection_creator_relationship }
    end
  end

  # GET /collection_creator_relationships/new
  # GET /collection_creator_relationships/new.json
  def new
    @collection_creator_relationship = CollectionCreatorRelationship.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @collection_creator_relationship }
    end
  end

  # GET /collection_creator_relationships/1/edit
  def edit
    @collection_creator_relationship = CollectionCreatorRelationship.find(params[:id])
  end

  # POST /collection_creator_relationships
  # POST /collection_creator_relationships.json
  def create
    @collection_creator_relationship = CollectionCreatorRelationship.new(params[:collection_creator_relationship])

    respond_to do |format|
      if @collection_creator_relationship.save
        format.html { redirect_to @collection_creator_relationship, notice: 'Collection creator relationship was successfully created.' }
        format.json { render json: @collection_creator_relationship, status: :created, location: @collection_creator_relationship }
      else
        format.html { render action: "new" }
        format.json { render json: @collection_creator_relationship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /collection_creator_relationships/1
  # PUT /collection_creator_relationships/1.json
  def update
    @collection_creator_relationship = CollectionCreatorRelationship.find(params[:id])

    respond_to do |format|
      if @collection_creator_relationship.update_attributes(params[:collection_creator_relationship])
        format.html { redirect_to @collection_creator_relationship, notice: 'Collection creator relationship was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @collection_creator_relationship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collection_creator_relationships/1
  # DELETE /collection_creator_relationships/1.json
  def destroy
    @collection_creator_relationship = CollectionCreatorRelationship.find(params[:id])
    @collection_creator_relationship.destroy

    respond_to do |format|
      format.html { redirect_to collection_creator_relationships_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/collection_creator_relationships_helper.rb
module CollectionCreatorRelationshipsHelper
end

app/views/collection_creator_relationships/_form.html.erb
<%= form_for(@collection_creator_relationship) do |f| %>
  <% if @collection_creator_relationship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@collection_creator_relationship.errors.count, "error") %> prohibited this collection_creator_relationship from being saved:</h2>

      <ul>
      <% @collection_creator_relationship.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :collection_id %><br />
    <%= f.number_field :collection_id %>
  </div>
  <div class="field">
    <%= f.label :creator_id %><br />
    <%= f.number_field :creator_id %>
  </div>
  <div class="field">
    <%= f.label :primary_creator %><br />
    <%= f.check_box :primary_creator %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/collection_creator_relationships/edit.html.erb
<h1>Editing collection_creator_relationship</h1>

<%= render 'form' %>

<%= link_to 'Show', @collection_creator_relationship %> |
<%= link_to 'Back', collection_creator_relationships_path %>

app/views/collection_creator_relationships/index.html.erb
<h1>Listing collection_creator_relationships</h1>

<table>
  <tr>
    <th>Collection</th>
    <th>Creator</th>
    <th>Primary creator</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @collection_creator_relationships.each do |collection_creator_relationship| %>
  <tr>
    <td><%= collection_creator_relationship.collection_id %></td>
    <td><%= collection_creator_relationship.creator_id %></td>
    <td><%= collection_creator_relationship.primary_creator %></td>
    <td><%= link_to 'Show', collection_creator_relationship %></td>
    <td><%= link_to 'Edit', edit_collection_creator_relationship_path(collection_creator_relationship) %></td>
    <td><%= link_to 'Destroy', collection_creator_relationship, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Collection creator relationship', new_collection_creator_relationship_path %>

app/views/collection_creator_relationships/new.html.erb
<h1>New collection_creator_relationship</h1>

<%= render 'form' %>

<%= link_to 'Back', collection_creator_relationships_path %>

app/views/collection_creator_relationships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Collection:</b>
  <%= @collection_creator_relationship.collection_id %>
</p>

<p>
  <b>Creator:</b>
  <%= @collection_creator_relationship.creator_id %>
</p>

<p>
  <b>Primary creator:</b>
  <%= @collection_creator_relationship.primary_creator %>
</p>


<%= link_to 'Edit', edit_collection_creator_relationship_path(@collection_creator_relationship) %> |
<%= link_to 'Back', collection_creator_relationships_path %>